name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Git
      run: apk add --no-cache git
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'
    - name: Test
      run: go test -v ./...
